---
title: "About Me"
---

## Background

<!-- CHANGE THIS -->
My name is Yogi Patnaik and I am a Master of Urban Spatial Analytics student at the University of Pennsylvania. I completed my Bachelor's degree in geographic information science (GIS) from Arizona State University. I have been fond of maps and how much information they hold since I was young. This inspired me to look into what more I could accomplish using that location data, which led me into becoming a GIS student. As a MUSA student, I wish to be even more creative with how I can analyze location data and be better able to use the various tools that are used in the realm of the urban spatial analytics program. My topics of interest when it comes to the spatial world is the design of better roadways and the creation of better urban sustainability patterns and sustainable transportation networks.  

## Skills

<!-- CHANGE THIS: update this through the semester as it becomes true -->

- **Languages & Tools:** R, Quarto, Git
- **Spatial:** (add as you learn)
- **Data:** US Census / ACS via `tidycensus`

## Contact

<!-- CHANGE THIS -->

- Email: ypatnaik@upenn.edu
- GitHub: [@ypatnaik1](https://github.com/ypatnaik1)
