{
  "hash": "903cceeaf3cc5d28f0d8914d2ddbee38",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Yogi Patnaik\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n\nIn this analysis, I look at median gross rent across counties in California and compare how reliable the estimates are. I use the margin of error to identify which counties have more or less uncertainty in their rent estimates.\n\n---\n\n\n\n\n\n```r\nvars <- load_variables(2023, \"acs5\")\nView(vars)\n```\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"CA\"       \nmy_variable <- \"B25064_001\"    \n\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 58  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                         variable   estimate   moe\n  <chr> <chr>                        <chr>         <dbl> <dbl>\n1 06001 Alameda County, California   B25064_001     2318    17\n2 06003 Alpine County, California    B25064_001       NA    NA\n3 06005 Amador County, California    B25064_001     1380   106\n4 06007 Butte County, California     B25064_001     1369    31\n5 06009 Calaveras County, California B25064_001     1615   142\n6 06011 Colusa County, California    B25064_001     1139    67\n```\n\n\n:::\n:::\n\n\n\nThe state of California has 58 counties, and the row count was also 58.\n\n\n\n\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                         estimate   moe moe_pct\n   <chr>                           <dbl> <dbl>   <dbl>\n 1 Sierra County, California        1181   705   59.7 \n 2 Trinity County, California        922   220   23.9 \n 3 Plumas County, California        1034   148   14.3 \n 4 Mono County, California          1593   212   13.3 \n 5 Mariposa County, California      1268   165   13.0 \n 6 Calaveras County, California     1615   142    8.79\n 7 Modoc County, California          818    71    8.68\n 8 Lake County, California          1292   110    8.51\n 9 Tuolumne County, California      1247   103    8.26\n10 Inyo County, California          1140    88    7.72\n```\n\n\n:::\n:::\n\n\n\n\n\nSierra County had the largest margin of error relative to the estimate, with a margin of error percentage of 59.7%.\n\n---\n\n Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    39\n2 Low confidence      6\n3 Moderate           13\n```\n\n\n:::\n:::\n\n\n\n\n\n**[How many counties fall into each category?]**\nFrom the total 58 counties in California, 39 counties were classified as high confidence, 13 as moderate confidence, and 6 as low confidence.\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                         myvarE myvarM    popE  popM\n  <chr> <chr>                         <dbl>  <dbl>   <dbl> <dbl>\n1 06001 Alameda County, California     2318     17 1651949    NA\n2 06003 Alpine County, California        NA     NA    1695   234\n3 06005 Amador County, California      1380    106   41029    NA\n4 06007 Butte County, California       1369     31  209470    NA\n5 06009 Calaveras County, California   1615    142   45995    NA\n6 06011 Colusa County, California      1139     67   21895    NA\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         39        989118.\n2 Low confidence           6         11691.\n3 Moderate                13         45926.\n```\n\n\n:::\n:::\n\n\n\n\n\n** [What is the average population of high-confidence counties versus low-confidence\ncounties? Is there a pattern?]**\n\nThe average population of high confidence counties is  989,117.82, and the average population of low confidence is  11,691.33. The pattern shows that less reliable estimates tend to occur in counties that have smaller populations.\n\n---\n\n\n\n We know the least about the smaller counties in California. Sierra County had a highest margin of error relative to its median gross rent estimate at 59.7%, and other smaller counties, like Trinity County, Plumas County, Mariposa County, and Mono County, had very high margins of error. These six counties, which were classified as low confidence had an average county population of 11,691. \n\n Since the ACS only uses a sample of households rather than surveying every household in the country, there is less samples and therefore more uncertainty and larger margins of error when collecting data. The smaller counties having less reliable median gross rent estimates is explained by this.\n\n This uncertainty plays a part in a situation where housing funding may be allocated based on an equally certain approach from a state agency. The high margins of error means that these smaller communities may be subjected to either too much money or too little money. Since the government has limited funding, a county receiving too much money can be detrimental to other counties who may need it. This ties into a county receiving too little money, because since their margin of error is not accounted for, the misallocation of funds further spirals.\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}